#!/bin/bash
# breachlab-ghost-watchdog.sh
# Auto-restore + alert on tampering of every baked file under /home/ghost*.
# Runs every 5 minutes via systemd timer.
#
# Inventory source: /etc/breachlab-ghost-watchdog/sources/snapshot.meta
#   (regenerated by /usr/local/sbin/extract-ghost-sources.sh after image rebuild)
# Path-byte copies live under .../sources/snapshot/ mirroring the container layout.

set -u

CONTAINER="breachlab-ghost"
SNAPSHOT_DIR=/etc/breachlab-ghost-watchdog/sources/snapshot
META_FILE=/etc/breachlab-ghost-watchdog/sources/snapshot.meta
LOG=/var/log/breachlab-ghost-watchdog.log
ENV_FILE=/etc/breachlab-invariants.env

# Directories on every ghostN home that must keep mode 700.
declare -a LOCKED_DIR_PATTERNS=("/home/ghostN" "/home/ghostN/.cache" "/home/ghostN/.ssh")

ALERTS=()
log() { printf '[%s] %s\n' "$(date -Iseconds)" "$*" >>"$LOG"; }
alert() { ALERTS+=("$1"); log "ALERT: $1"; }
dexec() { docker exec "$CONTAINER" "$@"; }

if [ ! -r "$META_FILE" ]; then
    log "FATAL: meta missing $META_FILE — run /usr/local/sbin/extract-ghost-sources.sh"
    exit 1
fi

# 1. Per-file integrity loop
while IFS=$'\t' read -r path meta; do
    [ -z "$path" ] && continue
    owner=$(awk '{print $1}' <<<"$meta")
    mode=$(awk '{print $2}' <<<"$meta")

    if [ "$mode" = "DIR" ]; then
        # ghost21 repo handled separately below
        continue
    fi

    src="$SNAPSHOT_DIR$path"
    exists=$(dexec test -e "$path" && echo y || echo n)

    if [ "$exists" = "n" ]; then
        if [ ! -r "$src" ]; then
            alert "Missing $path AND host source $src absent — manual rebuild needed."
            continue
        fi
        log "Restoring $path from snapshot"
        # Parent dir may need recreation in pathological cases (rare).
        parent=$(dirname "$path")
        dexec mkdir -p "$parent" 2>/dev/null || true
        docker cp "$src" "$CONTAINER:$path"
        dexec chown "$owner" "$path"
        dexec chmod "$mode" "$path"
        dexec chattr +i "$path"
        alert "Restored missing $path"
        continue
    fi

    # Exists — verify chattr +i. Idempotent (chattr +i on already-immutable is silent OK).
    attrs=$(dexec lsattr "$path" 2>/dev/null | awk '{print $1}')
    case "$attrs" in
        *i*) : ;;
        *)
            dexec chattr +i "$path" 2>/dev/null || true
            alert "Re-applied chattr +i on $path"
            ;;
    esac
done < "$META_FILE"

# 2. ghost21 repo — restore the entire git tree if .git missing
if dexec test -d /home/ghost21/repo/.git 2>/dev/null; then
    : # healthy
else
    if [ -d "$SNAPSHOT_DIR/home/ghost21/repo" ]; then
        log "Restoring /home/ghost21/repo from snapshot"
        dexec rm -rf /home/ghost21/repo 2>/dev/null || true
        docker cp "$SNAPSHOT_DIR/home/ghost21/repo" "$CONTAINER:/home/ghost21/repo"
        dexec chown -R ghost21:ghost21 /home/ghost21/repo
        # Re-immutable each baked file inside the repo
        dexec find /home/ghost21/repo -maxdepth 6 -type f -print0 \
            | dexec xargs -0 -r chattr +i 2>/dev/null || true
        alert "Restored /home/ghost21/repo"
    else
        alert "ghost21 repo missing AND no host snapshot — manual rebuild needed."
    fi
fi

# 3. Sweep mode drift on every ghostN home + .cache + .ssh (must be 700)
for i in $(seq 0 22); do
    for d in "/home/ghost$i" "/home/ghost$i/.cache" "/home/ghost$i/.ssh"; do
        cur=$(dexec stat -c %a "$d" 2>/dev/null) || continue
        if [ "$cur" != "700" ]; then
            dexec chmod 700 "$d"
            alert "Fixed mode drift $d $cur -> 700"
        fi
    done
done

# 4. Telegram alert if any drift fired
if [ ${#ALERTS[@]} -gt 0 ] && [ -r "$ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    if [ -n "${TG_BOT_TOKEN:-}" ] && [ -n "${TG_CHAT_ID:-}" ]; then
        msg=$'\xF0\x9F\x91\xBB Ghost watchdog drift detected:\n'
        for a in "${ALERTS[@]}"; do
            msg+="• $a"$'\n'
        done
        curl -sS -X POST \
            "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TG_CHAT_ID}" \
            -d text="$msg" >/dev/null || true
    fi
fi

exit 0
